/**
 * Guest access
 *
 * Visitors without an account can browse tenders and see real fit scores. The
 * guest id is generated by the browser and is therefore attacker-controlled,
 * so the whole design rests on it carrying no authority.
 *
 * These tests assert on the resolved request context rather than on status
 * codes, because "was this caller granted an identity?" is the property that
 * matters and a status code cannot express it.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { Hono, type MiddlewareHandler } from "hono";
import type { Env } from "../../app";

const verifyClerkToken = vi.fn();
vi.mock("../../lib/clerk", () => ({
  verifyClerkToken: (...a: unknown[]) => verifyClerkToken(...a),
}));

const { guestOrAuthMiddleware, requireAccount } = await import(
  "../../middleware/guest"
);
const { GUEST_ORG_ID, toScoringProfile } = await import("../../lib/guest");

/** Run the middleware and report the context it produced. */
function probe(mw: MiddlewareHandler<Env>) {
  const app = new Hono<Env>();
  app.use("*", mw);
  app.get("/", (c) =>
    c.json({
      userId: c.get("userId") ?? null,
      orgId: c.get("orgId") ?? null,
      guestId: c.get("guest")?.id ?? null,
      guestProfileOrg: c.get("guest")?.profile?.organization_id ?? null,
      guestCpv: c.get("guest")?.profile?.cpv_codes ?? null,
    })
  );
  return app;
}

/** Encode a guest profile the way the client will. */
const encodeProfile = (p: unknown) =>
  Buffer.from(JSON.stringify(p), "utf8").toString("base64url");

beforeEach(() => {
  vi.clearAllMocks();
  verifyClerkToken.mockResolvedValue({ success: false, error: "invalid" });
});

describe("a guest is never granted an identity", () => {
  it("establishes a guest context with no userId or org", async () => {
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: { "x-guest-id": "abc123" },
    });
    const ctx = await res.json();

    expect(ctx.guestId).toBe("abc123");
    expect(ctx.userId).toBeNull();
    expect(ctx.orgId).toBeNull();
  });

  it("ignores x-user-id entirely", async () => {
    // The header that used to be trusted globally. It must not resurface as a
    // way to act as another user just because guests are now allowed through.
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: { "x-user-id": "user_395HbXA1E11WhNTHbx3H0MJaC6C" },
    });
    const ctx = await res.json();

    expect(ctx.userId).toBeNull();
    expect(ctx.orgId).toBeNull();
  });

  it("does not let a guest id impersonate a Clerk user id", async () => {
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: { "x-guest-id": "user_395HbXA1E11WhNTHbx3H0MJaC6C" },
    });
    const ctx = await res.json();

    // It may be echoed as a guest id, but it confers nothing.
    expect(ctx.userId).toBeNull();
    expect(ctx.orgId).toBeNull();
  });

  it("gives a guest profile a sentinel org that matches no real row", async () => {
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: {
        "x-guest-profile": encodeProfile({ cpvCodes: ["72000000"] }),
      },
    });
    const ctx = await res.json();

    expect(ctx.guestProfileOrg).toBe(GUEST_ORG_ID);
    // Not a UUID, so it cannot collide with organizations.id.
    expect(ctx.guestProfileOrg).not.toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
    );
  });

  it("refuses to let a guest supply their own organization_id", async () => {
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: {
        "x-guest-profile": encodeProfile({
          cpvCodes: ["72000000"],
          organization_id: "11111111-1111-1111-1111-111111111111",
        }),
      },
    });
    const ctx = await res.json();

    expect(ctx.guestProfileOrg).toBe(GUEST_ORG_ID);
  });
});

describe("a valid session still wins", () => {
  it("produces a normal authenticated context", async () => {
    verifyClerkToken.mockResolvedValue({
      success: true,
      user: { userId: "user_real", orgId: "org_real", orgRole: "org:admin" },
    });

    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: { Authorization: "Bearer good-token", "x-guest-id": "abc" },
    });
    const ctx = await res.json();

    expect(ctx.userId).toBe("user_real");
    expect(ctx.guestId).toBeNull();
  });

  it("401s a bad token instead of silently downgrading to guest", async () => {
    // Downgrading would show an expired session someone else's view of the
    // product rather than telling them to sign in again.
    verifyClerkToken.mockResolvedValue({
      success: false,
      error: "token expired",
    });

    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: { Authorization: "Bearer expired-token" },
    });

    expect(res.status).toBe(401);
  });
});

describe("guest id validation", () => {
  it.each([
    ["oversized", "x".repeat(65)],
    ["path traversal", "../../etc/passwd"],
    ["injection-ish", "abc'; DROP TABLE--"],
    ["whitespace only", "   "],
  ])("falls back to anonymous for a %s id", async (_label, id) => {
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: { "x-guest-id": id },
    });
    const ctx = await res.json();

    // Rejected ids must not reach rate-limit keys or logs verbatim.
    expect(ctx.guestId).toBe("anonymous");
  });

  it("accepts an ordinary opaque id", async () => {
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: { "x-guest-id": "a1B2-c3_D4" },
    });
    expect((await res.json()).guestId).toBe("a1B2-c3_D4");
  });
});

describe("guest profile parsing", () => {
  it("reads a well-formed profile", async () => {
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: {
        "x-guest-profile": encodeProfile({
          cpvCodes: ["72000000", "48000000"],
          operatingRegions: ["ITA"],
          annualRevenue: 500000,
        }),
      },
    });

    expect((await res.json()).guestCpv).toEqual(["72000000", "48000000"]);
  });

  it.each([
    ["not base64", "!!!not-base64!!!"],
    ["not JSON", Buffer.from("hello", "utf8").toString("base64url")],
    ["wrong types", encodeProfile({ cpvCodes: "not-an-array" })],
    ["oversized", "A".repeat(5000)],
  ])("degrades to no profile for %s", async (_label, header) => {
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: { "x-guest-profile": header },
    });

    // Malformed input means "no profile", not a failed request: scoring
    // already explains which fields are missing.
    expect(res.status).toBe(200);
    expect((await res.json()).guestProfileOrg).toBeNull();
  });

  it("caps array sizes so a profile cannot be used to bloat scoring", async () => {
    const res = await probe(guestOrAuthMiddleware).request("/", {
      headers: {
        "x-guest-profile": encodeProfile({
          cpvCodes: Array.from({ length: 500 }, (_, i) => `${i}`),
        }),
      },
    });

    expect((await res.json()).guestProfileOrg).toBeNull();
  });
});

describe("requireAccount", () => {
  it("blocks a guest with a signup prompt, not a 401", async () => {
    const app = new Hono<Env>();
    app.use("*", guestOrAuthMiddleware);
    app.use("*", requireAccount);
    app.get("/", (c) => c.json({ ok: true }));

    const res = await app.request("/");
    const body = await res.json();

    // 403 not 401 so the client can tell "needs an account" from "session
    // expired" and show the right prompt.
    expect(res.status).toBe(403);
    expect(body.code).toBe("ACCOUNT_REQUIRED");
    expect(body.message).toMatch(/account/i);
  });

  it("lets a signed-in user through", async () => {
    verifyClerkToken.mockResolvedValue({
      success: true,
      user: { userId: "user_real", orgId: "org_real" },
    });

    const app = new Hono<Env>();
    app.use("*", guestOrAuthMiddleware);
    app.use("*", requireAccount);
    app.get("/", (c) => c.json({ ok: true }));

    const res = await app.request("/", {
      headers: { Authorization: "Bearer good" },
    });

    expect(res.status).toBe(200);
  });
});

describe("guest profiles are scoring-shaped but not persistable", () => {
  it("produces a profile the scoring engine accepts", () => {
    const profile = toScoringProfile({
      cpvCodes: ["72000000"],
      operatingRegions: ["ITA"],
      annualRevenue: 1_000_000,
    });

    expect(profile.cpv_codes).toEqual(["72000000"]);
    expect(profile.organization_id).toBe(GUEST_ORG_ID);
    expect(profile.completeness_score).toBeGreaterThan(0);
  });

  it("reports completeness so the UI can nudge for better scores", () => {
    const sparse = toScoringProfile({ cpvCodes: ["72000000"] });
    const full = toScoringProfile({
      cpvCodes: ["72000000"],
      operatingRegions: ["ITA"],
      certifications: ["ISO 9001"],
      annualRevenue: 1_000_000,
      employeeCount: 20,
      yearsInBusiness: 8,
    });

    expect(full.completeness_score).toBeGreaterThan(sparse.completeness_score);
    expect(full.completeness_score).toBe(100);
  });
});
