/**
 * Guest Sessions
 *
 * Lets a visitor try the product — search tenders, see real fit scores and
 * eligibility — without creating an account.
 *
 * A guest is NOT an authenticated user. The guest id is generated by the
 * browser and is therefore attacker-controlled, so it carries no authority
 * whatsoever: it exists only to give abuse controls something to key on. The
 * invariants below are what keep this from becoming the header-spoofing hole
 * that `x-user-id` used to be.
 *
 *   1. A guest context never carries a userId or an organization_id.
 *   2. A guest profile is supplied per request and is never written to the
 *      database, so it cannot collide with or overwrite a real profile.
 *   3. Guests reach read-only routes only; writes require a real account.
 *
 * Because the profile arrives with the request, guest scoring is real — the
 * same engine, the visitor's own numbers — without anything being persisted.
 */

import { z } from "zod";
import type { DbCompanyProfile } from "./db/company-profiles";

// ---------------------------------------------------------------------------
// Guest profile
// ---------------------------------------------------------------------------

/**
 * The handful of fields the scoring engine actually needs, collected from a
 * short inline form rather than the full onboarding wizard.
 */
export const guestProfileSchema = z.object({
  cpvCodes: z.array(z.string().max(16)).max(20).optional(),
  operatingRegions: z.array(z.string().max(64)).max(30).optional(),
  certifications: z.array(z.string().max(64)).max(20).optional(),
  annualRevenue: z.number().nonnegative().max(1e12).nullable().optional(),
  employeeCount: z.number().int().nonnegative().max(1e6).nullable().optional(),
  yearsInBusiness: z.number().int().nonnegative().max(500).nullable().optional(),
  contractSizeMin: z.number().nonnegative().max(1e12).nullable().optional(),
  contractSizeMax: z.number().nonnegative().max(1e12).nullable().optional(),
  companyName: z.string().max(200).optional(),
});

export type GuestProfileInput = z.infer<typeof guestProfileSchema>;

/** Request-scoped identity for a visitor without an account. */
export interface GuestContext {
  /** Browser-generated id. Carries no authority; used only for abuse control. */
  id: string;
  /** Profile supplied with this request, if any. Never persisted. */
  profile: DbCompanyProfile | null;
}

/**
 * Sentinel organization id for guest contexts.
 *
 * The scoring engine takes a DbCompanyProfile, which is typed with an
 * organization_id. Using an explicit non-UUID sentinel rather than a blank or
 * borrowed value means that if this ever reaches a query by mistake it matches
 * nothing, and it is obvious in logs.
 */
export const GUEST_ORG_ID = "guest:no-organization";

/**
 * Adapt a guest's inline form input to the shape the scoring engine expects.
 *
 * Fields the visitor did not supply stay null/empty, which the engine already
 * handles — it degrades those components and explains what is missing rather
 * than failing.
 */
export function toScoringProfile(
  input: GuestProfileInput
): DbCompanyProfile {
  const now = new Date().toISOString();

  return {
    id: "guest",
    organization_id: GUEST_ORG_ID,
    company_name: input.companyName || "Azienda ospite",
    description: null,
    industry: null,
    annual_revenue: input.annualRevenue ?? null,
    employee_count: input.employeeCount ?? null,
    legal_form: null,
    years_in_business: input.yearsInBusiness ?? null,
    website: null,
    cpv_codes: input.cpvCodes ?? [],
    certifications: input.certifications ?? [],
    technical_skills: [],
    operating_regions: input.operatingRegions ?? [],
    services: [],
    contract_size_min: input.contractSizeMin ?? null,
    contract_size_max: input.contractSizeMax ?? null,
    completeness_score: guestCompleteness(input),
    created_at: now,
    updated_at: now,
  };
}

/**
 * Rough completeness for the guest form, so the UI can nudge toward the
 * fields that most improve scoring.
 */
export function guestCompleteness(input: GuestProfileInput): number {
  const checks = [
    (input.cpvCodes?.length ?? 0) > 0,
    (input.operatingRegions?.length ?? 0) > 0,
    (input.certifications?.length ?? 0) > 0,
    input.annualRevenue != null,
    input.employeeCount != null,
    input.yearsInBusiness != null,
  ];
  return Math.round((checks.filter(Boolean).length / checks.length) * 100);
}

/**
 * Parse a guest profile from an untrusted request payload.
 *
 * Returns null rather than throwing: a malformed profile should degrade to
 * "no profile supplied" (scores explain what is missing), not 400 the request.
 */
export function parseGuestProfile(raw: unknown): DbCompanyProfile | null {
  if (!raw || typeof raw !== "object") return null;

  const parsed = guestProfileSchema.safeParse(raw);
  if (!parsed.success) return null;

  return toScoringProfile(parsed.data);
}

/** True when this profile came from a guest and must never be persisted. */
export function isGuestProfile(profile: DbCompanyProfile | null): boolean {
  return profile?.organization_id === GUEST_ORG_ID;
}
